### ISSUE TITLE
Not an editor command: belowleft

### ISSUE THREAD

**Issue by oguzbilgic** [pakutoma/toggle-terminal#4]
Not sure if this is a neovim command or something, but with the latest version of vim, `belowleft` isn't available. And `:toggleTerminal` command doesn't work

![Screen Shot 2020-10-22 at 3 42 51 PM](https://user-images.githubusercontent.com/144778/96937603-5c7b8b00-147d-11eb-9232-62ee2bdef5f5.png)

**Comment by pakutoma** [comment]
Thanks!
This command seems to have been removed by some vim update.
I think the `botright` command has the same meaning, I'll replace it.

Please let me know if you have any problems.
